// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0asPRjt_hBycWQGedKBVAYSKzlcP4zqw',
    appId: '1:287073465288:web:b4e0f93d04d5f7252a06fd',
    messagingSenderId: '287073465288',
    projectId: 'brain-app-sb',
    authDomain: 'brain-app-sb.firebaseapp.com',
    storageBucket: 'brain-app-sb.appspot.com',
    measurementId: 'G-BT025RZ0PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWiviWI8iw2dkXfgq39ojEajfLQlyMygo',
    appId: '1:287073465288:android:713dfc7fd330d5572a06fd',
    messagingSenderId: '287073465288',
    projectId: 'brain-app-sb',
    storageBucket: 'brain-app-sb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvrOAkjXoseGFfElb1Sel5xr1AQse05pI',
    appId: '1:287073465288:ios:e166020d565f6b782a06fd',
    messagingSenderId: '287073465288',
    projectId: 'brain-app-sb',
    storageBucket: 'brain-app-sb.appspot.com',
    androidClientId: '287073465288-l73k4p5bjvqpmu5l1j3lrup1v6fct0pi.apps.googleusercontent.com',
    iosClientId: '287073465288-cct3vi7ujg50s9ej10kd36muj2qv5thr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
